my:
  name: forezp
  age: 12
  number:  ${random.int}
  uuid : ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'm  ${my.name}

zcssc:
  config:
      session:
          ruyi:
            driverKey: webdriver.chrome.driver
            driverValueFile: D:\lxf\my-study-workspace\zcssc\src\main\resources\chromedriver.exe
            url: https://www-ry999.com/
            userName: a920259310
            passWord: a19931006

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zcssc?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    hikari:
      username: root
      password: root

mapper:
    plugin: tk.mybatis.mapper.generator.MapperPlugin
    Mapper: tk.mybatis.mapper.common.Mapper
    mappers: com.springboot.zcssc.zcssc.common.mybatis.mapper.IBaseMapper
    not-empty: false
    identity: MYSQL
mybatis:
    type-aliases-package: com.springboot.zcssc.zcssc.bean.db
    mapper-locations: classpath:mybatis/mapper/*.xml


logging:
  config: classpath:logback-boot.xml

profiles:
    active: test